# see https://docs.travis-ci.com/user/languages/php/ for more hints
language: php

php:
  - 7.4
  - 8.0
#  - 8.1

before_script:
  - composer self-update
  - composer install

script:
  - XDEBUG_MODE=coverage php vendor/bin/phpunit --configuration phpunit.xml --coverage-clover php-tests/data/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --format=txt --verbose --diff --allow-risky=yes --config=.php-cs-fixer.dist.php
  - vendor/bin/phpstan analyse -c phpstan.neon

notifications:
  email: "me@kalanys.com"
