<?php

namespace kalanis\UploadPerPartes\GenerateKeys;


use kalanis\UploadPerPartes\Interfaces\IDriverLocation;


/**
 * Class Random
 * @package kalanis\UploadPerPartes\GenerateKeys
 * Connect shared key and local which has been generated by as random string
 */
class Random extends AKey
{
    /** @var int */
    protected $keyLength = 64;

    /** @var string[] */
    public static $possibilities = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'];

    public function generateKey(IDriverLocation $data): string
    {
        return $this->generateRandomText($this->keyLength, static::$possibilities);
    }

    /**
     * @param int $length
     * @param string[] $possibilities
     * @return string
     */
    public static function generateRandomText(int $length, array $possibilities): string
    {
        $string = '';
        for ($i = 0; $i < $length; $i++) {
            $rand = mt_rand(0, count($possibilities) - 1);
            $string .= $possibilities[$rand];
        }
        return $string;
    }
}
